import {
  SignIn,
  SignInButton,
  SignOutButton,
  SignedOut,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something Went Wrong!</div>;

  return (
    <>
      <Head>
        <title>Potato-x</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className=" h-full w-full border-x-2 border-slate-400 bg-teal-900 md:max-w-2xl">
          <div className=" static flex flex-row justify-between border-b-2 border-slate-400">
            <div className=" right-0 top-0 p-4 ">
              <UserButton afterSignOutUrl="/" />
            </div>
            {!user.isSignedIn && (
              <div className=" p-4">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className=" p-4">
                <SignOutButton />
              </div>
            )}
          </div>

          <div className="flex flex-col">
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className="  border-b-2 border-slate-400 p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
